language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
script: py.test
env:
  - SMOOCH_SECRET=smooch_secret SMOOCH_KEY_ID=smooch_key_id
before_install:
  - pip install -e .
